web1: subcontract --rbenv . --chdir ../development  --signal INT -- bundle exec thin start -p 8080 -e $RACK_ENV &
web2: subcontract --rbenv . --chdir ../api          --signal INT -- bundle exec thin start -p 9090 -e $RACK_ENV &
