PROCEDURE_CODES = {
  D1110: 'Prophylaxis-adult',
  D1120: 'Prophylaxis-child',
  D0120: 'Periodic Oral Evaluation - Established P',
  D1206: 'Topical Fluoride Varnish; Therapeutic Ap',
  D1208: 'Topical Application of Fluoride',
  D1351: 'Sealant-per Tooth',
  D0140: 'Limited Oral Evaluation- P.F.',
  D0150: 'Comprehensive Oral Evaluation - New Or E',
  D0210: 'Intraoral-complete Series',
  D2140: 'Amalgam - One Surface',
  D2150: 'Amalgam - Two Surfaces',
  D2160: 'Amalgam - Three Surfaces',
  D2161: 'Amalgam - Four Or More Surfaces',
  D0220: 'Intraoral-periapical-1st Image',
  D0230: 'Intraoral-periapical/add`l Image',
  D2330: 'Resin-one Surface, Anterior',
  D2331: 'Resin-two Surfaces, Anterior',
  D2332: 'Resin-three Surfaces, Anterior',
  D2391: '1 surface posterior resin',
  D2392: '2 surface posterior resin',
  D2393: '3 surface posterior resin',
  D0272: 'Bitewings-two Images',
  D0274: 'Bitewings-four Images',
  D2750: 'Crown-porcelain- CAPTEK',
  D2931: 'Prefab S/s Crown-perm Tooth',
  D2950: 'Core Buildup, Including Pins',
  D2954: 'Prefabricated Post & Core',
  D0330: 'Panoramic Image',
  D3310: 'Anterior (excl Final Rest)',
  D3320: 'Bicuspid (excl Final Rest)',
  D3330: 'Molar (excluding Final Rest)',
  D3348: 'Retreat Of Root Canal, Molar',
  D4342: 'Periodontal Scaling And Root Planing - O',
  D4355: 'Full Mouth Debridement To Enable Compreh',
  D4910: 'Periodontal Maintenance',
  D5110: 'Complete Denture - Maxillary',
  D5120: 'Complete Denture - Mandibular',
  D5130: 'Immediate Denture - Maxillary',
  D5213: 'Max Partial-cast Metal B',
  D5214: 'Mand Partial-cast Metal B',
  D5640: 'Replace Broken Tooth',
  D5731: 'Reline Complete Mand Denture',
  D6240: 'Pontic-porcelain/high Noble Mt',
  D6750: 'Crown-porcelain Fused To H N M',
  D7140: 'Simple Extraction',
  D71210: 'Surgical Removal Erupted Tooth',
  D7220: 'Removal Imp Tooth-soft Tissue',
  D7230: 'Removal Imp Tooth-part Bony',
  D7510: 'Incision/drainage Of Abscess',
  D7971: 'Exc Of Pericoronal Gingiva',
  D9110: 'Palliative (Emer) Treatment',
  D9230: 'Analgesia, Anxiolysis, Inhalation Of Nit',
  D9430: 'Office Visit For Observation'
}