dosespots: &dosespots
  dose_server:                            <%= ENV["DOSESPOT_SERVER"] %>
  dose_url:                               <%= ENV["DOSESPOT_URL"] %>
  dose_b:                                 <%= ENV["DOSESPOT_B"] %>
  dose_b_param:                           <%= ENV["DOSESPOT_B_PARAM"] %>
  dose_clinic_id_param:                   <%= ENV["DOSESPOT_CLINIC_ID_PARAM"] %>
  dose_clinic_id:                         <%= ENV["DOSESPOT_CLINIC_ID"] %>
  dose_clinic_key:                        <%= ENV["DOSESPOT_CLINIC_KEY"] %>
  dose_user_id_param:                     <%= ENV["DOSESPOT_USER_ID_PARAM"] %>
  dose_phrase_length_param:               <%= ENV["DOSESPOT_PHRASE_LENGTH_PARAM"] %>
  dose_phrase_length:                     <%= ENV["DOSESPOT_PHRASE_LENGTH"] %>
  dose_code_param:                        <%= ENV["DOSESPOT_CODE_PARAM"] %>
  dose_user_id_verify_param:              <%= ENV["DOSESPOT_USER_ID_VERIFY_PARAM"] %>
  dose_user_id_verify:                    <%= ENV["DOSESPOT_USER_ID_VERIFY"] %>
  dose_prefix_param:                      <%= ENV["DOSESPOT_PREFIX_PARAM"] %>
  dose_prefix:                            <%= ENV["DOSESPOT_PREFIX"] %>
  dose_first_name_param:                  <%= ENV["DOSESPOT_FIRST_NAME_PARAM"] %>
  dose_middle_name_param:                 <%= ENV["DOSESPOT_MIDDLE_NAME_PARAM"] %>
  dose_last_name_param:                   <%= ENV["DOSESPOT_LAST_NAME_PARAM"] %>
  dose_suffix_param:                      <%= ENV["DOSESPOT_SUFFIX_PARAM"] %>
  dose_suffix:                            <%= ENV["DOSESPOT_SUFFIX"] %>
  dose_birth_param:                       <%= ENV["DOSESPOT_BIRTH_PARAM"] %>
  dose_gender_param:                      <%= ENV["DOSESPOT_GENDER_PARAM"] %>
  dose_first_address_param:               <%= ENV["DOSESPOT_FIRST_ADDRESS_PARAM"] %>
  dose_first_address:                     <%= ENV["DOSESPOT_FIRST_ADDRESS"] %>
  dose_second_address_param:              <%= ENV["DOSESPOT_SECOND_ADDRESS_PARAM"] %>
  dose_second_address:                    <%= ENV["DOSESPOT_SECOND_ADDRESS"] %>
  dose_city_param:                        <%= ENV["DOSESPOT_CITY_PARAM"] %>
  dose_city:                              <%= ENV["DOSESPOT_CITY"] %>
  dose_state_param:                       <%= ENV["DOSESPOT_STATE_PARAM"] %>
  dose_state:                             <%= ENV["DOSESPOT_STATE"] %>
  dose_zipcode_param:                     <%= ENV["DOSESPOT_ZIPCODE_PARAM"] %>
  dose_zipcode:                           <%= ENV["DOSESPOT_ZIPCODE"] %>
  dose_primary_phone_param:               <%= ENV["DOSESPOT_PRIMARY_PHONE_PARAM"] %>
  dose_primary_phone:                     <%= ENV["DOSESPOT_PRIMARY_PHONE"] %>
  dose_primary_phone_type_param:          <%= ENV["DOSESPOT_PRIMARY_PHONE_TYPE_PARAM"] %>
  dose_primary_phone_type:                <%= ENV["DOSESPOT_PRIMARY_PHONE_TYPE"] %>
  dose_first_phone_additional_param:      <%= ENV["DOSESPOT_FIRST_PHONE_ADDITIONAL_PARAM"] %>
  dose_first_phone_additional:            <%= ENV["DOSESPOT_FIRST_PHONE_ADDITIONAL"] %>
  dose_first_phone_additional_type_param: <%= ENV["DOSESPOT_FIRST_PHONE_ADDITIONAL_TYPE_PARAM"] %>
  dose_first_phone_additional_type:       <%= ENV["DOSESPOT_FIRST_PHONE_ADDITIONAL_TYPE"] %>
  dose_pharmacy_id_param:                 <%= ENV["DOSESPOT_PHARMACY_ID_PARAM"] %>
  dose_pharmacy_id:                       <%= ENV["DOSESPOT_PHARMACY_ID"] %>

development:
  default_email_reply:      <%= ENV["DEFAULT_EMAIL_REPLY"] %>
  gmail_email:              <%= ENV["GMAIL_EMAIL"] %>
  gmail_password:           <%= ENV["GMAIL_PASSWORD"] %>
  admin_email:              <%= ENV["ADMIN_EMAIL"] %>
  admin_password:           <%= ENV["ADMIN_PASSWORD"] %>
  admin_phone_number:       <%= ENV["ADMIN_PHONE_NUMBER"] %>
  admin_country_code:       <%= ENV["ADMIN_COUNTRY_CODE"] %>
  domain_name:              <%= ENV["DOMAIN_NAME_DEVELOPMENT"] %>
  authy_api_key:            <%= ENV["AUTHY_API_KEY"] %>
  authy_api_host:           <%= ENV["AUTHY_API_HOST"] %>
  twilio_account_sid:       <%= ENV["TWILIO_ACCOUNT_SID"] %>
  twilio_auth_token:        <%= ENV["TWILIO_AUTH_TOKEN"] %>
  twilio_phone_number:      <%= ENV["TWILIO_PHONE_NUMBER"] %>
  ehr_provider_email:       <%= ENV["EHR_PROVIDER_EMAIL"] %>
  ehr_provider_password:    <%= ENV["EHR_PROVIDER_PASSWORD"] %>
  ehr_practice_email:       <%= ENV["EHR_PRACTICE_EMAIL"] %>
  ehr_practice_password:    <%= ENV["EHR_PRACTICE_PASSWORD"] %>
  ehr_patient_email:        <%= ENV["EHR_PATIENT_EMAIL"] %>
  ehr_patient_password:     <%= ENV["EHR_PATIENT_PASSWORD"] %>
  info_email:               <%= ENV["INFO_EMAIL"] %>
  localhost:                <%= ENV["LOCALHOST"] %>
  mailcatcher_port:         <%= ENV["MAILCATCHER_PORT"] %>
  rethinkdb_url:            <%= ENV["RETHINKDB_URL"] %>
  rethinkdb_host:           <%= ENV["RETHINKDB_HOST"] %>
  rethinkdb_port:           <%= ENV["RETHINKDB_PORT"] %>
  rethinkdb_db:             <%= ENV["RETHINKDB_DB"] %>
  secret_key_base:          <%= ENV["SECRET_KEY_BASE_DEVELOPMENT"] %>
  <<: *dosespots

test:
  domain_name:              <%= ENV["DOMAIN_NAME_TEST"] %>
  secret_key_base:          <%= ENV["SECRET_KEY_BASE_TEST"] %>
  rethinkdb_url:            <%= ENV["RETHINKDB_URL"] %>
  localhost_name:           <%= ENV["LOCALHOST_NAME_TEST"] %>
  <<: *dosespots

production:
  default_email_reply:      <%= ENV["DEFAULT_EMAIL_REPLY"] %>
  gmail_email:              <%= ENV["GMAIL_EMAIL"] %>
  gmail_password:           <%= ENV["GMAIL_PASSWORD"] %>
  admin_email:              <%= ENV["ADMIN_EMAIL"] %>
  admin_password:           <%= ENV["ADMIN_PASSWORD"] %>
  admin_phone_number:       <%= ENV["ADMIN_PHONE_NUMBER"] %>
  admin_country_code:       <%= ENV["ADMIN_COUNTRY_CODE"] %>
  domain_name:              <%= ENV["DOMAIN_NAME"] %>
  authy_api_key:            <%= ENV["AUTHY_API_KEY"] %>
  authy_api_host:           <%= ENV["AUTHY_API_HOST"] %>
  twilio_account_sid:       <%= ENV["TWILIO_ACCOUNT_SID"] %>
  twilio_auth_token:        <%= ENV["TWILIO_AUTH_TOKEN"] %>
  twilio_phone_number:      <%= ENV["TWILIO_PHONE_NUMBER"] %>
  sendgrid_address:         <%= ENV["SENDGRID_ADDRESS"] %>
  sendgrid_port:            <%= ENV["SENDGRID_PORT"] %>
  sendgrid_domain:          <%= ENV["SENDGRID_DOMAIN"] %>
  sendgrid_username:        <%= ENV["SENDGRID_USERNAME"] %>
  sendgrid_password:        <%= ENV["SENDGRID_PASSWORD"] %>
  sendgrid_authentication:  <%= ENV["SENDGRID_AUTHENTICATION"] %>
  sendgrid_api_user:        <%= ENV["SENDGRID_API_USER"] %>
  sendgrid_api_key:         <%= ENV["SENDGRID_API_KEY"] %>
  ehr_provider_email:       <%= ENV["EHR_PROVIDER_EMAIL"] %>
  ehr_provider_password:    <%= ENV["EHR_PROVIDER_PASSWORD"] %>
  ehr_practice_email:       <%= ENV["EHR_PRACTICE_EMAIL"] %>
  ehr_practice_password:    <%= ENV["EHR_PRACTICE_PASSWORD"] %>
  ehr_patient_email:        <%= ENV["EHR_PATIENT_EMAIL"] %>
  ehr_patient_password:     <%= ENV["EHR_PATIENT_PASSWORD"] %>
  info_email:               <%= ENV["INFO_EMAIL"] %>
  rethinkdb_host:           <%= ENV["RETHINKDB_HOST"] %>
  rethinkdb_port:           <%= ENV["RETHINKDB_PORT"] %>
  rethinkdb_db:             <%= ENV["RETHINKDB_DB"] %>
  secret_key_base:          <%= ENV["SECRET_KEY_BASE_PRODUCTION"] %>
  <<: *dosespots
