development:
  default_email_reply:      <%= ENV["DEFAULT_EMAIL_REPLY"] %>
  gmail_email:              <%= ENV["GMAIL_EMAIL"] %>
  gmail_password:           <%= ENV["GMAIL_PASSWORD"] %>
  admin_email:              <%= ENV["ADMIN_EMAIL"] %>
  admin_password:           <%= ENV["ADMIN_PASSWORD"] %>
  admin_phone_number:       <%= ENV["ADMIN_PHONE_NUMBER"] %>
  admin_country_code:       <%= ENV["ADMIN_COUNTRY_CODE"] %>
  admin_email_subject:      <%= ENV["ADMIN_EMAIL_SUBJECT"] %>
  domain_name:              <%= ENV["DOMAIN_NAME_DEVELOPMENT"] %>
  authy_api_key:            <%= ENV["AUTHY_API_KEY"] %>
  authy_api_host:           <%= ENV["AUTHY_API_HOST"] %>
  twilio_account_sid:       <%= ENV["TWILIO_ACCOUNT_SID"] %>
  twilio_auth_token:        <%= ENV["TWILIO_AUTH_TOKEN"] %>
  twilio_phone_number:      <%= ENV["TWILIO_PHONE_NUMBER"] %>
  ehr_provider_email:       <%= ENV["EHR_PROVIDER_EMAIL"] %>
  ehr_provider_password:    <%= ENV["EHR_PROVIDER_PASSWORD"] %>
  ehr_practice_email:       <%= ENV["EHR_PRACTICE_EMAIL"] %>
  ehr_practice_password:    <%= ENV["EHR_PRACTICE_PASSWORD"] %>
  ehr_patient_email:        <%= ENV["EHR_PATIENT_EMAIL"] %>
  ehr_patient_password:     <%= ENV["EHR_PATIENT_PASSWORD"] %>
  info_email:               <%= ENV["INFO_EMAIL"] %>
  localhost:                <%= ENV["LOCALHOST"] %>
  mailcatcher_port:         <%= ENV["MAILCATCHER_PORT"] %>
  mail_subject:             <%= ENV["MAIL_SUBJECT"] %>
  mail_user_welcome:        <%= ENV["MAIL_USER_WELCOME"] %>
  rethinkdb_url:            <%= ENV["RETHINKDB_URL"] %>
  rethinkdb_db:             <%= ENV["RETHINKDB_DB"] %>
  secret_key_base:          <%= ENV["SECRET_KEY_BASE_DEVELOPMENT"] %>

test:
  default_email_reply:      <%= ENV["DEFAULT_EMAIL_REPLY"] %>
  gmail_email:              <%= ENV["GMAIL_EMAIL"] %>
  gmail_password:           <%= ENV["GMAIL_PASSWORD"] %>
  admin_email:              <%= ENV["ADMIN_EMAIL"] %>
  admin_password:           <%= ENV["ADMIN_PASSWORD"] %>
  admin_phone_number:       <%= ENV["ADMIN_PHONE_NUMBER"] %>
  admin_country_code:       <%= ENV["ADMIN_COUNTRY_CODE"] %>
  admin_email_subject:      <%= ENV["ADMIN_EMAIL_SUBJECT"] %>
  domain_name:              <%= ENV["DOMAIN_NAME_DEVELOPMENT"] %>
  authy_api_key:            <%= ENV["AUTHY_API_KEY"] %>
  authy_api_host:           <%= ENV["AUTHY_API_HOST"] %>
  twilio_account_sid:       <%= ENV["TWILIO_ACCOUNT_SID"] %>
  twilio_auth_token:        <%= ENV["TWILIO_AUTH_TOKEN"] %>
  twilio_phone_number:      <%= ENV["TWILIO_PHONE_NUMBER"] %>
  ehr_provider_email:       <%= ENV["EHR_PROVIDER_EMAIL"] %>
  ehr_provider_password:    <%= ENV["EHR_PROVIDER_PASSWORD"] %>
  ehr_practice_email:       <%= ENV["EHR_PRACTICE_EMAIL"] %>
  ehr_practice_password:    <%= ENV["EHR_PRACTICE_PASSWORD"] %>
  ehr_patient_email:        <%= ENV["EHR_PATIENT_EMAIL"] %>
  ehr_patient_password:     <%= ENV["EHR_PATIENT_PASSWORD"] %>
  info_email:               <%= ENV["INFO_EMAIL"] %>
  localhost:                <%= ENV["LOCALHOST"] %>
  mailcatcher_port:         <%= ENV["MAILCATCHER_PORT"] %>
  mail_subject:             <%= ENV["MAIL_SUBJECT"] %>
  mail_user_welcome:        <%= ENV["MAIL_USER_WELCOME"] %>
  rethinkdb_url:            <%= ENV["RETHINKDB_URL"] %>
  rethinkdb_db:             <%= ENV["RETHINKDB_DB"] %>
  secret_key_base:          <%= ENV["SECRET_KEY_BASE_DEVELOPMENT"] %>

production:
  default_email_reply:      <%= ENV["DEFAULT_EMAIL_REPLY"] %>
  gmail_email:              <%= ENV["GMAIL_EMAIL"] %>
  gmail_password:           <%= ENV["GMAIL_PASSWORD"] %>
  admin_email:              <%= ENV["ADMIN_EMAIL"] %>
  admin_password:           <%= ENV["ADMIN_PASSWORD"] %>
  admin_phone_number:       <%= ENV["ADMIN_PHONE_NUMBER"] %>
  admin_country_code:       <%= ENV["ADMIN_COUNTRY_CODE"] %>
  admin_email_subject:      <%= ENV["ADMIN_EMAIL_SUBJECT"] %>
  domain_name:              <%= ENV["DOMAIN_NAME"] %>
  authy_api_key:            <%= ENV["AUTHY_API_KEY"] %>
  authy_api_host:           <%= ENV["AUTHY_API_HOST"] %>
  twilio_account_sid:       <%= ENV["TWILIO_ACCOUNT_SID"] %>
  twilio_auth_token:        <%= ENV["TWILIO_AUTH_TOKEN"] %>
  twilio_phone_number:      <%= ENV["TWILIO_PHONE_NUMBER"] %>
  sendgrid_address:         <%= ENV["SENDGRID_ADDRESS"] %>
  sendgrid_port:            <%= ENV["SENDGRID_PORT"] %>
  sendgrid_domain:          <%= ENV["SENDGRID_DOMAIN"] %>
  sendgrid_username:        <%= ENV["SENDGRID_USERNAME"] %>
  sendgrid_password:        <%= ENV["SENDGRID_PASSWORD"] %>
  sendgrid_authentication:  <%= ENV["SENDGRID_AUTHENTICATION"] %>
  sendgrid_api_user:        <%= ENV["SENDGRID_API_USER"] %>
  sendgrid_api_key:         <%= ENV["SENDGRID_API_KEY"] %>
  ehr_provider_email:       <%= ENV["EHR_PROVIDER_EMAIL"] %>
  ehr_provider_password:    <%= ENV["EHR_PROVIDER_PASSWORD"] %>
  ehr_practice_email:       <%= ENV["EHR_PRACTICE_EMAIL"] %>
  ehr_practice_password:    <%= ENV["EHR_PRACTICE_PASSWORD"] %>
  ehr_patient_email:        <%= ENV["EHR_PATIENT_EMAIL"] %>
  ehr_patient_password:     <%= ENV["EHR_PATIENT_PASSWORD"] %>
  info_email:               <%= ENV["INFO_EMAIL"] %>
  mail_subject:             <%= ENV["MAIL_SUBJECT"] %>
  mail_user_welcome:        <%= ENV["MAIL_USER_WELCOME"] %>
  rethinkdb_host:           <%= ENV["RETHINKDB_HOST"] %>
  rethinkdb_port:           <%= ENV["RETHINKDB_PORT"] %>
  rethinkdb_db:             <%= ENV["RETHINKDB_DB"] %>
  secret_key_base:          <%= ENV["SECRET_KEY_BASE_PRODUCTION"] %>
